version: 1
formatters:
  my_default:
    # Enter the tab as it is (don't use "\t")
    format: '%(asctime)s  %(name)-12s %(funcName)s  %(levelname)-8s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: my_default
    filters: [trace_cut_filter] # filters are defined in logconfig.py
loggers:
  package1.module1_1:
    level: DEBUG
    handlers: [console]
  package2:
    level: DEBUG
    handlers: [console]